// lib/mockData.ts
// PRAM OS — Fuente única de datos mock para Demo / Offline
// VERSION 4.0 — Unificado (eliminado src/data/mockData.js)

import {
  Estudiante,
  Mentor,
  Sesion,
  ExamenDiagnostico,
  Supervisor,
  SolicitudRefuerzo,
} from '@/types/pram'

export const mockSupervisores: Supervisor[] = [
  {
    id: 'sup-1',
    nombre: 'Dirección del Liceo Minerva Mirabal',
    area: 'Matemáticas',
    codigo_acceso: 'DIR-2026',
  },
]

export const mockMentores: Mentor[] = [
  {
    id: 'm-1',
    nombre: 'Prof. Altagracia Peña',
    rango: 'Head',
    horas_acumuladas: 48.5,
    especialidad: 'Matemáticas',
    supervisor_id: 'sup-1',
    puntos_ranking: 585,
  },
  {
    id: 'm-2',
    nombre: 'Lic. Marcos Santana',
    rango: 'Senior',
    horas_acumuladas: 34.0,
    especialidad: 'Lengua Española',
    supervisor_id: 'sup-1',
    puntos_ranking: 440,
  },
  {
    id: 'm-3',
    nombre: 'Ing. Sofía Castillo',
    rango: 'Junior',
    horas_acumuladas: 19.5,
    especialidad: 'Matemáticas',
    supervisor_id: 'sup-1',
    puntos_ranking: 295,
  },
]

export const mockEstudiantes: Estudiante[] = [
  {
    id: 'e-1',
    nombre: 'Carlos Reyes',
    pin: '1234',
    grado: '3ro',
    liceo_seccion: 'Liceo Minerva Mirabal · 3ro B',
    nivel_actual: 3,
    mentor_id: 'm-1',
    nivel_pretest: 2,
    nivel_posttest: 4,
    puntos_ranking: 160,
    racha_asistencia: 4,
    graduado_pram: false,
  },
  {
    id: 'e-2',
    nombre: 'Yomaira Gómez',
    pin: '5678',
    grado: '4to',
    liceo_seccion: 'Liceo Minerva Mirabal · 4to A',
    nivel_actual: 1,
    mentor_id: 'm-1',
    nivel_pretest: 1,
    nivel_posttest: 2,
    puntos_ranking: 45,
    racha_asistencia: 1,
    graduado_pram: false,
  },
  {
    id: 'e-3',
    nombre: 'Franklin Tejeda',
    pin: '9012',
    grado: '3ro',
    liceo_seccion: 'Liceo Minerva Mirabal · 3ro A',
    nivel_actual: 5,
    mentor_id: 'm-2',
    nivel_pretest: 3,
    nivel_posttest: 5,
    puntos_ranking: 290,
    racha_asistencia: 6,
    graduado_pram: true,
  },
  {
    id: 'e-4',
    nombre: 'Valerie Rosario',
    pin: '3456',
    grado: '3ro',
    liceo_seccion: 'Liceo Minerva Mirabal · 3ro C',
    nivel_actual: 4,
    mentor_id: 'm-3',
    nivel_pretest: 2,
    nivel_posttest: 4,
    puntos_ranking: 230,
    racha_asistencia: 5,
    graduado_pram: false,
  },
]

export const mockSesiones: Sesion[] = [
  {
    id: 's-1',
    estudiante_id: 'e-1',
    mentor_id: 'm-1',
    tema: 'Resolución de Ecuaciones Lineales con Una Incógnita',
    materia: 'Matemáticas',
    fecha_programada: '14 ago 2026 · 3:30 PM',
    duracion_minutos: 45,
    estado: 'Completada',
    confirmacion_mentor: true,
    confirmacion_estudiante: true,
    validado_por_auditoria: true,
    estado_auditoria: 'Aprobado_Institucional',
    notas: 'Despeje de variables y práctica de 5 ejercicios guiados.',
  },
  {
    id: 's-2',
    estudiante_id: 'e-2',
    mentor_id: 'm-1',
    tema: 'Operaciones Fundamentales con Fracciones y Decimales',
    materia: 'Matemáticas',
    fecha_programada: '15 ago 2026 · 4:15 PM',
    duracion_minutos: 45,
    estado: 'Programada',
    confirmacion_mentor: true,
    confirmacion_estudiante: false,
    validado_por_auditoria: false,
    estado_auditoria: 'Pendiente',
    notas: 'Refuerzo de fracciones complejas y jerarquía de operaciones.',
  },
  {
    id: 's-3',
    estudiante_id: 'e-3',
    mentor_id: 'm-2',
    tema: 'Análisis de Textos Literarios y Figuras Retóricas',
    materia: 'Lengua Española',
    fecha_programada: '15 ago 2026 · 5:00 PM',
    duracion_minutos: 45,
    estado: 'Completada',
    confirmacion_mentor: true,
    confirmacion_estudiante: true,
    validado_por_auditoria: false,
    estado_auditoria: 'Pendiente',
    notas: 'Comprensión textual y redacción de argumentos.',
  },
  {
    id: 's-4',
    estudiante_id: 'e-4',
    mentor_id: 'm-3',
    tema: 'Factorización de Polinomios Cuadráticos',
    materia: 'Matemáticas',
    fecha_programada: '16 ago 2026 · 3:00 PM',
    duracion_minutos: 45,
    estado: 'Programada',
    confirmacion_mentor: false,
    confirmacion_estudiante: false,
    validado_por_auditoria: false,
    estado_auditoria: 'Pendiente',
    notas: 'Práctica de trinomios con forma ax² + bx + c.',
  },
]

export const mockSolicitudes: SolicitudRefuerzo[] = [
  {
    id: 'sol-1',
    estudiante_id: 'e-1',
    tema: 'Despeje de ecuaciones con fracciones',
    materia: 'Matemáticas',
    fecha_solicitud: '15 ago 2026',
    estado: 'Pendiente',
  },
  {
    id: 'sol-2',
    estudiante_id: 'e-2',
    tema: 'Suma y resta de fracciones heterogéneas',
    materia: 'Matemáticas',
    fecha_solicitud: '14 ago 2026',
    estado: 'Asignada',
  },
]

export const mockExamenes: ExamenDiagnostico[] = [
  {
    id: 'ex-1',
    estudiante_id: 'e-1',
    tipo: 'Pre-Test',
    variante: 'A',
    fecha: '10 ago 2026',
    resultado_nivel: 2,
    ai_analysis_summary: 'Despeje básico comprendido, debilidad en números negativos.',
    foto_url: '',
  },
  {
    id: 'ex-2',
    estudiante_id: 'e-3',
    tipo: 'Post-Test',
    variante: 'B',
    fecha: '13 ago 2026',
    resultado_nivel: 5,
    ai_analysis_summary: 'Dominio completo. Listo para graduación PRAM.',
    foto_url: '',
  },
]
